safaris:
    salesTaxRate: 0.20    # Sales tax rate.
    deliveryCharge: 
        normal: 2.50      # Delivery charge (GBP) on normal deliveries.
        threshold: 3000   # Threshold cart value (GBP), for free delivery.